### ISSUE TITLE
Bug: JSON.stringify(...) adds extra qoutes for token value

### ISSUE THREAD

**Issue by denisbednov** [soofstad/react-oauth2-pkce#191] opened 2024-10-11 17:16 UTC
### Token from auth service:
![image](https://github.com/user-attachments/assets/7110c40e-702b-41d5-9536-fefad239d3d3)

![image](https://github.com/user-attachments/assets/2e60606b-599c-40fc-a220-81ef08de70e6)

### JSON.stringify(token) with doubled qoutes:
![image](https://github.com/user-attachments/assets/636277e4-4cac-493d-846c-7db6a88029dd)

### Session storage:
![image](https://github.com/user-attachments/assets/60cd0981-9804-42bd-a8a2-59c9d5478473)

## Steps To Reproduce

1. Login with PKCE;
2. Check browser storage for value.

## The current behavior
Token value corrupted.

## The expected behavior
Token value has no extra quotes.

**Comment by sebastianvitterso** [comment] 2024-10-14 04:26
Hi, @denisbednov!
I believe this is a duplicate of https://github.com/soofstad/react-oauth2-pkce/issues/182, so if you'll have a read on that issue, I think you'll find that this isn't a bug. 
The local/session-storage storing of values is an implementation detail, and not part of the exposed API - so even though we probably won't change it much, it's not something we guarantee will remain unchanged.
I'll leave the issue open so we can see if this is the same issue or not :v:

**Comment by denisbednov** [comment] 2024-10-21 08:20
Hi, @sebastianvitterso!
Thanks for solution. Could you close this issue?

**Closed** 2024-10-21 08:33 UTC
