### ISSUE TITLE
AutoLogin Needs fixing

### ISSUE THREAD

**Issue by ghauri899** [soofstad/react-oauth2-pkce#57] opened 2023-01-05 18:14 UTC
Hi,
Just wanted to share my expierence with AutoLogin.
 
So I was implementing the package as specified in the document where I encountered an issue with the autoLogin Param of this package.
What happens is that when we open our home page (in my case localhost:3000). Autologin which is set to TRUE redirects user to the required authentication point. But if the user after being redirecting, doesnot log in and tries to open home page again(localhost:3000), autoLogin fails to redirect him this time. The interesting thing is Now If the user refreshes his page (meaning that, he is loading the page for the third time), autoLogin will work and user will be redirected to the authentication point.
Summarizing, On Odd number of Page load count, autologin works. On even numbers, it doesnt.

Steps to replicate:
I replicated this using both of the examples given by you guyz on github but I changed the autoLogin to TRUE. 
- Load localhost:3000 -> You will be redirected to authenticator. Now dont log in there. Just go back to localhost: 3000 without logging in. This time you wont be ridrected. Now refresh your page and voila you will be.

**Comment by soofstad** [comment] 2023-01-06 07:08
Hi there,
This is working as intended.
If the login process in aborted in some way, this library will have a "bad state". This is returned in the `error` object from the AuthContext, and says just what you described; "Bad authorization state. Refreshing the page might solve the issue."

It's done in this way to avoid any infinite login loops. If that happens, the AuthProvider is likely to block either the user or the entire app (client_id) for a while. And also your app would be unusable.

If you have any suggestions on how to handle this in a more robust manner, I'd be happy for any ideas :slightly_smiling_face:

**Comment by sebastianvitterso** [comment] 2023-01-16 05:35
@ghauri899 Do you have any further suggestions, feel free to comment here. 

For now, I'm closing the issue.

**Closed by sebastianvitterso** 2023-01-16 05:35 UTC
